INSERT INTO `countries` (`id`, `alpha_2`, `alpha_3`, `name`, `created_at`, `updated_at`) VALUES
(4, 'AF', 'AFG', 'Afghanistan', NOW(), NOW()),
(8, 'AL', 'ALB', 'Albania', NOW(), NOW()),
(10, 'AQ', 'ATA', 'Antarctica', NOW(), NOW()),
(12, 'DZ', 'DZA', 'Algeria', NOW(), NOW()),
(16, 'AS', 'ASM', 'American Samoa', NOW(), NOW()),
(20, 'AD', 'AND', 'Andorra', NOW(), NOW()),
(24, 'AO', 'AGO', 'Angola', NOW(), NOW()),
(28, 'AG', 'ATG', 'Antigua and Barbuda', NOW(), NOW()),
(31, 'AZ', 'AZE', 'Azerbaijan', NOW(), NOW()),
(32, 'AR', 'ARG', 'Argentina', NOW(), NOW()),
(36, 'AU', 'AUS', 'Australia', NOW(), NOW()),
(40, 'AT', 'AUT', 'Austria', NOW(), NOW()),
(44, 'BS', 'BHS', 'Bahamas', NOW(), NOW()),
(48, 'BH', 'BHR', 'Bahrain', NOW(), NOW()),
(50, 'BD', 'BGD', 'Bangladesh', NOW(), NOW()),
(51, 'AM', 'ARM', 'Armenia', NOW(), NOW()),
(52, 'BB', 'BRB', 'Barbados', NOW(), NOW()),
(56, 'BE', 'BEL', 'Belgium', NOW(), NOW()),
(60, 'BM', 'BMU', 'Bermuda', NOW(), NOW()),
(64, 'BT', 'BTN', 'Bhutan', NOW(), NOW()),
(68, 'BO', 'BOL', 'Bolivia', NOW(), NOW()),
(70, 'BA', 'BIH', 'Bosnia and Herzegovina', NOW(), NOW()),
(72, 'BW', 'BWA', 'Botswana', NOW(), NOW()),
(74, 'BV', 'BVT', 'Bouvet Island', NOW(), NOW()),
(76, 'BR', 'BRA', 'Brazil', NOW(), NOW()),
(84, 'BZ', 'BLZ', 'Belize', NOW(), NOW()),
(86, 'IO', 'IOT', 'British Indian Ocean Territory', NOW(), NOW()),
(90, 'SB', 'SLB', 'Solomon Islands', NOW(), NOW()),
(92, 'VG', 'VGB', 'Virgin Islands, British', NOW(), NOW()),
(96, 'BN', 'BRN', 'Brunei Darussalam', NOW(), NOW()),
(100, 'BG', 'BGR', 'Bulgaria', NOW(), NOW()),
(104, 'MM', 'MMR', 'Myanmar', NOW(), NOW()),
(108, 'BI', 'BDI', 'Burundi', NOW(), NOW()),
(112, 'BY', 'BLR', 'Belarus', NOW(), NOW()),
(116, 'KH', 'KHM', 'Cambodia', NOW(), NOW()),
(120, 'CM', 'CMR', 'Cameroon', NOW(), NOW()),
(124, 'CA', 'CAN', 'Canada', NOW(), NOW()),
(132, 'CV', 'CPV', 'Cape Verde', NOW(), NOW()),
(136, 'KY', 'CYM', 'Cayman Islands', NOW(), NOW()),
(140, 'CF', 'CAF', 'Central African Republic', NOW(), NOW()),
(144, 'LK', 'LKA', 'Sri Lanka', NOW(), NOW()),
(148, 'TD', 'TCD', 'Chad', NOW(), NOW()),
(152, 'CL', 'CHL', 'Chile', NOW(), NOW()),
(156, 'CN', 'CHN', 'China', NOW(), NOW()),
(158, 'TW', 'TWN', 'Taiwan, Province of China', NOW(), NOW()),
(162, 'CX', 'CXR', 'Christmas Island', NOW(), NOW()),
(166, 'CC', 'CCK', 'Cocos (Keeling) Islands', NOW(), NOW()),
(170, 'CO', 'COL', 'Colombia', NOW(), NOW()),
(174, 'KM', 'COM', 'Comoros', NOW(), NOW()),
(175, 'YT', 'MYT', 'Mayotte', NOW(), NOW()),
(178, 'CG', 'COG', 'Congo', NOW(), NOW()),
(180, 'CD', 'COD', 'Congo, the Democratic Republic of the', NOW(), NOW()),
(184, 'CK', 'COK', 'Cook Islands', NOW(), NOW()),
(188, 'CR', 'CRI', 'Costa Rica', NOW(), NOW()),
(191, 'HR', 'HRV', 'Croatia', NOW(), NOW()),
(192, 'CU', 'CUB', 'Cuba', NOW(), NOW()),
(196, 'CY', 'CYP', 'Cyprus', NOW(), NOW()),
(203, 'CZ', 'CZE', 'Czech Republic', NOW(), NOW()),
(204, 'BJ', 'BEN', 'Benin', NOW(), NOW()),
(208, 'DK', 'DNK', 'Denmark', NOW(), NOW()),
(212, 'DM', 'DMA', 'Dominica', NOW(), NOW()),
(214, 'DO', 'DOM', 'Dominican Republic', NOW(), NOW()),
(218, 'EC', 'ECU', 'Ecuador', NOW(), NOW()),
(222, 'SV', 'SLV', 'El Salvador', NOW(), NOW()),
(226, 'GQ', 'GNQ', 'Equatorial Guinea', NOW(), NOW()),
(231, 'ET', 'ETH', 'Ethiopia', NOW(), NOW()),
(232, 'ER', 'ERI', 'Eritrea', NOW(), NOW()),
(233, 'EE', 'EST', 'Estonia', NOW(), NOW()),
(234, 'FO', 'FRO', 'Faroe Islands', NOW(), NOW()),
(238, 'FK', 'FLK', 'Falkland Islands (Malvinas)', NOW(), NOW()),
(239, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', NOW(), NOW()),
(242, 'FJ', 'FJI', 'Fiji', NOW(), NOW()),
(246, 'FI', 'FIN', 'Finland', NOW(), NOW()),
(248, 'AX', 'ALA', 'Åland Islands', NOW(), NOW()),
(250, 'FR', 'FRA', 'France', NOW(), NOW()),
(254, 'GF', 'GUF', 'French Guiana', NOW(), NOW()),
(258, 'PF', 'PYF', 'French Polynesia', NOW(), NOW()),
(260, 'TF', 'ATF', 'French Southern Territories', NOW(), NOW()),
(262, 'DJ', 'DJI', 'Djibouti', NOW(), NOW()),
(266, 'GA', 'GAB', 'Gabon', NOW(), NOW()),
(268, 'GE', 'GEO', 'Georgia', NOW(), NOW()),
(270, 'GM', 'GMB', 'Gambia', NOW(), NOW()),
(275, 'PS', 'PSE', 'Palestinian Territory, Occupied', NOW(), NOW()),
(276, 'DE', 'DEU', 'Germany', NOW(), NOW()),
(288, 'GH', 'GHA', 'Ghana', NOW(), NOW()),
(292, 'GI', 'GIB', 'Gibraltar', NOW(), NOW()),
(296, 'KI', 'KIR', 'Kiribati', NOW(), NOW()),
(300, 'GR', 'GRC', 'Greece', NOW(), NOW()),
(304, 'GL', 'GRL', 'Greenland', NOW(), NOW()),
(308, 'GD', 'GRD', 'Grenada', NOW(), NOW()),
(312, 'GP', 'GLP', 'Guadeloupe', NOW(), NOW()),
(316, 'GU', 'GUM', 'Guam', NOW(), NOW()),
(320, 'GT', 'GTM', 'Guatemala', NOW(), NOW()),
(324, 'GN', 'GIN', 'Guinea', NOW(), NOW()),
(328, 'GY', 'GUY', 'Guyana', NOW(), NOW()),
(332, 'HT', 'HTI', 'Haiti', NOW(), NOW()),
(334, 'HM', 'HMD', 'Heard Island and Mcdonald Islands', NOW(), NOW()),
(336, 'VA', 'VAT', 'Holy See (Vatican City State)', NOW(), NOW()),
(340, 'HN', 'HND', 'Honduras', NOW(), NOW()),
(344, 'HK', 'HKG', 'Hong Kong', NOW(), NOW()),
(348, 'HU', 'HUN', 'Hungary', NOW(), NOW()),
(352, 'IS', 'ISL', 'Iceland', NOW(), NOW()),
(356, 'IN', 'IND', 'India', NOW(), NOW()),
(360, 'ID', 'IDN', 'Indonesia', NOW(), NOW()),
(364, 'IR', 'IRN', 'Iran, Islamic Republic of', NOW(), NOW()),
(368, 'IQ', 'IRQ', 'Iraq', NOW(), NOW()),
(372, 'IE', 'IRL', 'Ireland', NOW(), NOW()),
(376, 'IL', 'ISR', 'Israel', NOW(), NOW()),
(380, 'IT', 'ITA', 'Italy', NOW(), NOW()),
(384, 'CI', 'CIV', 'Cote D''Ivoire', NOW(), NOW()),
(388, 'JM', 'JAM', 'Jamaica', NOW(), NOW()),
(392, 'JP', 'JPN', 'Japan', NOW(), NOW()),
(398, 'KZ', 'KAZ', 'Kazakhstan', NOW(), NOW()),
(400, 'JO', 'JOR', 'Jordan', NOW(), NOW()),
(404, 'KE', 'KEN', 'Kenya', NOW(), NOW()),
(408, 'KP', 'PRK', 'Korea, Democratic People''s Republic of', NOW(), NOW()),
(410, 'KR', 'KOR', 'Korea, Republic of', NOW(), NOW()),
(414, 'KW', 'KWT', 'Kuwait', NOW(), NOW()),
(417, 'KG', 'KGZ', 'Kyrgyzstan', NOW(), NOW()),
(418, 'LA', 'LAO', 'Lao People''s Democratic Republic', NOW(), NOW()),
(422, 'LB', 'LBN', 'Lebanon', NOW(), NOW()),
(426, 'LS', 'LSO', 'Lesotho', NOW(), NOW()),
(428, 'LV', 'LVA', 'Latvia', NOW(), NOW()),
(430, 'LR', 'LBR', 'Liberia', NOW(), NOW()),
(434, 'LY', 'LBY', 'Libyan Arab Jamahiriya', NOW(), NOW()),
(438, 'LI', 'LIE', 'Liechtenstein', NOW(), NOW()),
(440, 'LT', 'LTU', 'Lithuania', NOW(), NOW()),
(442, 'LU', 'LUX', 'Luxembourg', NOW(), NOW()),
(446, 'MO', 'MAC', 'Macao', NOW(), NOW()),
(450, 'MG', 'MDG', 'Madagascar', NOW(), NOW()),
(454, 'MW', 'MWI', 'Malawi', NOW(), NOW()),
(458, 'MY', 'MYS', 'Malaysia', NOW(), NOW()),
(462, 'MV', 'MDV', 'Maldives', NOW(), NOW()),
(466, 'ML', 'MLI', 'Mali', NOW(), NOW()),
(470, 'MT', 'MLT', 'Malta', NOW(), NOW()),
(474, 'MQ', 'MTQ', 'Martinique', NOW(), NOW()),
(478, 'MR', 'MRT', 'Mauritania', NOW(), NOW()),
(480, 'MU', 'MUS', 'Mauritius', NOW(), NOW()),
(484, 'MX', 'MEX', 'Mexico', NOW(), NOW()),
(492, 'MC', 'MCO', 'Monaco', NOW(), NOW()),
(496, 'MN', 'MNG', 'Mongolia', NOW(), NOW()),
(498, 'MD', 'MDA', 'Moldova, Republic of', NOW(), NOW()),
(499, 'ME', 'MNE', 'Montenegro', NOW(), NOW()),
(500, 'MS', 'MSR', 'Montserrat', NOW(), NOW()),
(504, 'MA', 'MAR', 'Morocco', NOW(), NOW()),
(508, 'MZ', 'MOZ', 'Mozambique', NOW(), NOW()),
(512, 'OM', 'OMN', 'Oman', NOW(), NOW()),
(516, 'NA', 'NAM', 'Namibia', NOW(), NOW()),
(520, 'NR', 'NRU', 'Nauru', NOW(), NOW()),
(524, 'NP', 'NPL', 'Nepal', NOW(), NOW()),
(528, 'NL', 'NLD', 'Netherlands', NOW(), NOW()),
(530, 'AN', 'ANT', 'Netherlands Antilles', NOW(), NOW()),
(531, 'CW', 'CUW', 'Curaçao      ', NOW(), NOW()),
(533, 'AW', 'ABW', 'Aruba', NOW(), NOW()),
(534, 'SX', 'SXM', 'Sint Maarten (Dutch part)   ', NOW(), NOW()),
(535, 'BQ', 'BES', 'Bonaire, Saint Eustatius and Saba  ', NOW(), NOW()),
(540, 'NC', 'NCL', 'New Caledonia', NOW(), NOW()),
(548, 'VU', 'VUT', 'Vanuatu', NOW(), NOW()),
(554, 'NZ', 'NZL', 'New Zealand', NOW(), NOW()),
(558, 'NI', 'NIC', 'Nicaragua', NOW(), NOW()),
(562, 'NE', 'NER', 'Niger', NOW(), NOW()),
(566, 'NG', 'NGA', 'Nigeria', NOW(), NOW()),
(570, 'NU', 'NIU', 'Niue', NOW(), NOW()),
(574, 'NF', 'NFK', 'Norfolk Island', NOW(), NOW()),
(578, 'NO', 'NOR', 'Norway', NOW(), NOW()),
(580, 'MP', 'MNP', 'Northern Mariana Islands', NOW(), NOW()),
(581, 'UM', 'UMI', 'United States Minor Outlying Islands', NOW(), NOW()),
(583, 'FM', 'FSM', 'Micronesia, Federated States of', NOW(), NOW()),
(584, 'MH', 'MHL', 'Marshall Islands', NOW(), NOW()),
(585, 'PW', 'PLW', 'Palau', NOW(), NOW()),
(586, 'PK', 'PAK', 'Pakistan', NOW(), NOW()),
(591, 'PA', 'PAN', 'Panama', NOW(), NOW()),
(598, 'PG', 'PNG', 'Papua New Guinea', NOW(), NOW()),
(600, 'PY', 'PRY', 'Paraguay', NOW(), NOW()),
(604, 'PE', 'PER', 'Peru', NOW(), NOW()),
(608, 'PH', 'PHL', 'Philippines', NOW(), NOW()),
(612, 'PN', 'PCN', 'Pitcairn', NOW(), NOW()),
(616, 'PL', 'POL', 'Poland', NOW(), NOW()),
(620, 'PT', 'PRT', 'Portugal', NOW(), NOW()),
(624, 'GW', 'GNB', 'Guinea-Bissau', NOW(), NOW()),
(626, 'TL', 'TLS', 'Timor-Leste', NOW(), NOW()),
(630, 'PR', 'PRI', 'Puerto Rico', NOW(), NOW()),
(634, 'QA', 'QAT', 'Qatar', NOW(), NOW()),
(638, 'RE', 'REU', 'Reunion', NOW(), NOW()),
(642, 'RO', 'ROM', 'Romania', NOW(), NOW()),
(643, 'RU', 'RUS', 'Russian Federation', NOW(), NOW()),
(646, 'RW', 'RWA', 'Rwanda', NOW(), NOW()),
(652, 'BL', 'BLM', 'Saint Barthélemy     ', NOW(), NOW()),
(654, 'SH', 'SHN', 'Saint Helena', NOW(), NOW()),
(659, 'KN', 'KNA', 'Saint Kitts and Nevis', NOW(), NOW()),
(660, 'AI', 'AIA', 'Anguilla', NOW(), NOW()),
(662, 'LC', 'LCA', 'Saint Lucia', NOW(), NOW()),
(663, 'MF', 'MAF', 'Saint Martin (French part)', NOW(), NOW()),
(666, 'PM', 'SPM', 'Saint Pierre and Miquelon', NOW(), NOW()),
(670, 'VC', 'VCT', 'Saint Vincent and the Grenadines', NOW(), NOW()),
(674, 'SM', 'SMR', 'San Marino', NOW(), NOW()),
(678, 'ST', 'STP', 'Sao Tome and Principe', NOW(), NOW()),
(682, 'SA', 'SAU', 'Saudi Arabia', NOW(), NOW()),
(686, 'SN', 'SEN', 'Senegal', NOW(), NOW()),
(688, 'RS', 'SRB', 'Serbia', NOW(), NOW()),
(690, 'SC', 'SYC', 'Seychelles', NOW(), NOW()),
(694, 'SL', 'SLE', 'Sierra Leone', NOW(), NOW()),
(702, 'SG', 'SGP', 'Singapore', NOW(), NOW()),
(703, 'SK', 'SVK', 'Slovakia', NOW(), NOW()),
(704, 'VN', 'VNM', 'Viet Nam', NOW(), NOW()),
(705, 'SI', 'SVN', 'Slovenia', NOW(), NOW()),
(706, 'SO', 'SOM', 'Somalia', NOW(), NOW()),
(710, 'ZA', 'ZAF', 'South Africa', NOW(), NOW()),
(716, 'ZW', 'ZWE', 'Zimbabwe', NOW(), NOW()),
(724, 'ES', 'ESP', 'Spain', NOW(), NOW()),
(732, 'EH', 'ESH', 'Western Sahara', NOW(), NOW()),
(736, 'SD', 'SDN', 'Sudan', NOW(), NOW()),
(740, 'SR', 'SUR', 'Suriname', NOW(), NOW()),
(744, 'SJ', 'SJM', 'Svalbard and Jan Mayen', NOW(), NOW()),
(748, 'SZ', 'SWZ', 'Swaziland', NOW(), NOW()),
(752, 'SE', 'SWE', 'Sweden', NOW(), NOW()),
(756, 'CH', 'CHE', 'Switzerland', NOW(), NOW()),
(760, 'SY', 'SYR', 'Syrian Arab Republic', NOW(), NOW()),
(762, 'TJ', 'TJK', 'Tajikistan', NOW(), NOW()),
(764, 'TH', 'THA', 'Thailand', NOW(), NOW()),
(768, 'TG', 'TGO', 'Togo', NOW(), NOW()),
(772, 'TK', 'TKL', 'Tokelau', NOW(), NOW()),
(776, 'TO', 'TON', 'Tonga', NOW(), NOW()),
(780, 'TT', 'TTO', 'Trinidad and Tobago', NOW(), NOW()),
(784, 'AE', 'ARE', 'United Arab Emirates', NOW(), NOW()),
(788, 'TN', 'TUN', 'Tunisia', NOW(), NOW()),
(792, 'TR', 'TUR', 'Turkey', NOW(), NOW()),
(795, 'TM', 'TKM', 'Turkmenistan', NOW(), NOW()),
(796, 'TC', 'TCA', 'Turks and Caicos Islands', NOW(), NOW()),
(798, 'TV', 'TUV', 'Tuvalu', NOW(), NOW()),
(800, 'UG', 'UGA', 'Uganda', NOW(), NOW()),
(804, 'UA', 'UKR', 'Ukraine', NOW(), NOW()),
(807, 'MK', 'MKD', 'Macedonia, the Former Yugoslav Republic of', NOW(), NOW()),
(818, 'EG', 'EGY', 'Egypt', NOW(), NOW()),
(826, 'GB', 'GBR', 'United Kingdom', NOW(), NOW()),
(831, 'GG', 'GGY', 'Guernsey      ', NOW(), NOW()),
(832, 'JE', 'JEY', 'Jersey', NOW(), NOW()),
(833, 'IM', 'IMN', 'Isle of Man    ', NOW(), NOW()),
(834, 'TZ', 'TZA', 'Tanzania, United Republic of', NOW(), NOW()),
(840, 'US', 'USA', 'United States', NOW(), NOW()),
(850, 'VI', 'VIR', 'Virgin Islands, U.s.', NOW(), NOW()),
(854, 'BF', 'BFA', 'Burkina Faso', NOW(), NOW()),
(858, 'UY', 'URY', 'Uruguay', NOW(), NOW()),
(860, 'UZ', 'UZB', 'Uzbekistan', NOW(), NOW()),
(862, 'VE', 'VEN', 'Venezuela', NOW(), NOW()),
(876, 'WF', 'WLF', 'Wallis and Futuna', NOW(), NOW()),
(882, 'WS', 'WSM', 'Samoa', NOW(), NOW()),
(887, 'YE', 'YEM', 'Yemen', NOW(), NOW()),
(891, 'CS', 'SCG', 'Serbia and Montenegro', NOW(), NOW()),
(894, 'ZM', 'ZMB', 'Zambia', NOW(), NOW());
